language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --bootstrap vendor/autoload.php Tests

notifications:
  email:
    - developer@blitzr.com
